INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ykumar/Desktop/nd064_course_1/exercises/python-helloworld/app.py", line 11, in health_check
    logging.debug("{}, {} endpoint was reached".format(datetime.datetime.now(), status))
NameError: name 'datetime' is not defined
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 17:50:17] "[35m[1mGET /status HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ykumar/Desktop/nd064_course_1/exercises/python-helloworld/app.py", line 12, in health_check
    logging.debug("{}, {} endpoint was reached".format(datetime.datetime.now(), status))
NameError: name 'status' is not defined
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 17:50:59] "[35m[1mGET /status HTTP/1.1[0m" 500 -
ERROR:app:Exception on /status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ykumar/Desktop/nd064_course_1/exercises/python-helloworld/app.py", line 12, in health_check
    logging.debug("{}, {} endpoint was reached".format(datetime.datetime.now(), status))
NameError: name 'status' is not defined
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 17:51:00] "[35m[1mGET /status HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
DEBUG:root:2021-06-07 17:51:39.515335, status endpoint was reached
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 17:51:39] "[37mGET /status HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
DEBUG:root:2021-06-07 18:09:33.241894, status endpoint was reached
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 18:09:33] "[37mGET /status HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:app:status request success
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 18:12:34] "[37mGET /status HTTP/1.1[0m" 200 -
INFO:app:status request success
INFO:werkzeug:127.0.0.1 - - [07/Jun/2021 18:14:12] "[37mGET /status HTTP/1.1[0m" 200 -
